### ISSUE TITLE
No games listed

### ISSUE THREAD

**Issue by fgblomqvist** [Mixaill/galaxy-integration-wargaming#28]
No games show up in GOG once I've signed in. I'm guessing it should probably list all of them? The link to Sentry in the readme doesn't work either 🙁 

Where can I see logs?

**Comment by Mixaill** [comment]
Fixed in v0.9.3

Try to unpack unpack
https://github.com/Mixaill/galaxy-integration-wargaming/releases/download/v0.9.3/galaxy-integration-wargaming_v0.9.3.zip

to `%localappdata%\GOG.com\Galaxy\plugins\installed\wargaming\`

@friendsofgalaxy can you push v0.9.3 to the client ASAP because it breaks game discovery.

**Comment by fgblomqvist** [comment]
Thank you!

**Comment by FriendsOfGalaxy** [comment]
@Mixaill push to `fog_release` branch.

If you want to sync with master, remove `fog_release`.

**Comment by Mixaill** [comment]
@FriendsOfGalaxy sorry, forgot about that. Pushed fog_release

**Comment by FriendsOfGalaxy** [comment]
Merged 👍
